
# 示例默认的日志配置参数
[logger]
#日志类的名字，日志文件以此作为前缀名字
log_name= logger
#日志保存时间的单位
when= D
# 日志保存时间的间隔
interval= 1
# 同一类型日志保留的数量
backup_count= 30
; 日志的输出格式
formatter= %(asctime)s- %(processName)s:%(process)d - %(threadName)s:%(thread)d - %(name)s - %(message)s
; 日志输出等级有 NOTSET INFO  WARNING ERROR CRITICAL
output_level=INFO